# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# automatically generated by gs-pypi
# please do not edit this file
#
# Original Author: Jauhien Piatlicki <jauhien@gentoo.org>
# Purpose: support installation of python packages from PyPI repo
#
# Bugs to jauhien@gentoo.org
#
# @ECLASS: gs-pypi.eclass
#

inherit distutils-r1 g-sorcery
